"""create campus table

Revision ID: bc9d0e62229b
Revises: 0b46556e634c
Create Date: 2025-05-29 13:06:40.558652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9d0e62229b'
down_revision: Union[str, None] = '0b46556e634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.add_column('teams', sa.Column('campus_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'teams', 'campus', ['campus_id'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'campus_id')
    op.drop_table('campus')
    # ### end Alembic commands ###
