"""nomeando fk campus_code

Revision ID: ea957b65f37a
Revises: bc9d0e62229b
Create Date: 2025-05-29 13:43:31.072711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea957b65f37a'
down_revision: Union[str, None] = 'bc9d0e62229b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('campus_code', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('teams_campus_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key('fk_teams_campus_code', 'teams', 'campus', ['campus_code'], ['code'])
    op.drop_column('teams', 'campus_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('campus_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_teams_campus_code', 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_campus_id_fkey'), 'teams', 'campus', ['campus_id'], ['code'])
    op.drop_column('teams', 'campus_code')
    # ### end Alembic commands ###
